//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angajat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Angajat()
        {
            this.Depart1 = new HashSet<Depart>();
        }
    
        public int marca { get; set; }
        public string nume { get; set; }
        public Nullable<System.DateTime> datanastere { get; set; }
        public Nullable<int> Iddep { get; set; }
        public Nullable<int> salariu { get; set; }
    
        public virtual Depart Depart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Depart> Depart1 { get; set; }
    }
}
